#!/usr/bin/env python3
import os
import shutil
import subprocess

preset = os.environ.get("LPM_PRESET", "default")
subprocess.run(["mkinitcpio", "-p", preset], check=True)

if shutil.which("bootctl"):
    subprocess.run(["bootctl", "update"], check=False)

if shutil.which("grub-mkconfig"):
    subprocess.run(["grub-mkconfig", "-o", "/boot/grub/grub.cfg"], check=False)
