#!/usr/bin/env python3
import os
import shutil
import subprocess


def main() -> None:
    tool = shutil.which("systemd-tmpfiles")
    if not tool:
        return
    root = os.environ.get("LPM_ROOT", "/")
    subprocess.run(
        [
            tool,
            "--create",
            "--remove",
            "--boot",
            "--root",
            root,
        ],
        check=False,
    )


if __name__ == "__main__":
    main()
