from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from collections import defaultdict, deque
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Any, Dict, Optional

from lpm.chroot import ChrootMountState, mount_chroot_api, umount_chroot_api

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover - exercised on Python 3.10
    import tomli as tomllib


class Stage(str, Enum):
    VALIDATE = "validate"
    PREPARE_DIRS = "prepare-dirs"
    SEED_LPM = "seed-lpm"
    RESOLVE_BUILD_PLAN = "resolve-build-plan"
    INSTALL_BASE = "install-base"
    CONFIGURE_SYSTEM = "configure-system"
    GENERATE_INITRAMFS = "generate-initramfs"
    INSTALL_BOOTLOADER = "install-bootloader"
    FINAL_CHECK = "final-check"


STAGES: list[Stage] = [
    Stage.VALIDATE,
    Stage.PREPARE_DIRS,
    Stage.SEED_LPM,
    Stage.RESOLVE_BUILD_PLAN,
    Stage.INSTALL_BASE,
    Stage.CONFIGURE_SYSTEM,
    Stage.GENERATE_INITRAMFS,
    Stage.INSTALL_BOOTLOADER,
    Stage.FINAL_CHECK,
]


@dataclass
class BootstrapConfig:
    target: Path
    hostname: Optional[str] = None
    timezone: Optional[str] = None
    locale: Optional[str] = None
    keymap: Optional[str] = None
    bootloader: Optional[str] = None
    kernel: Optional[str] = None
    config: Optional[Path] = None
    resume: bool = False
    dry_run: bool = False
    verbose: bool = False
    force: bool = False
    efi_dir: Optional[Path] = None
    boot_device: Optional[str] = None
    network: Optional[str] = None
    plan_file: Optional[Path] = None
    lpmbuild_root: Optional[Path] = None
    include_packages: tuple[str, ...] = ()
    exclude_packages: tuple[str, ...] = ()

    @property
    def state_path(self) -> Path:
        return self.target / "var/lib/lpm/bootstrap-state.json"


def _safe_target(target: Path) -> None:
    resolved = target.resolve()
    if str(resolved) in {"/", "/etc", "/usr", "/var", "/boot"}:
        raise ValueError(f"refusing dangerous target: {resolved}")


def _blkid_uuid(device: str) -> str | None:
    try:
        completed = subprocess.run(["blkid", "-s", "UUID", "-o", "value", device], check=False, capture_output=True, text=True)
    except OSError:
        return None
    return completed.stdout.strip() if completed.returncode == 0 and completed.stdout.strip() else None


def _fstab_source(device: str) -> str:
    return f"UUID={uuid}" if (uuid := _blkid_uuid(device)) else device


def generate_fstab(target: Path, boot_mode: str, efi_dir: Path | None, boot_device: dict[str, str]) -> Path:
    fstab_path = target / "etc/fstab"
    fstab_path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# /etc/fstab generated by lpm bootstrap"]
    if root_dev := boot_device.get("root"):
        lines.append(f"{_fstab_source(root_dev)} / ext4 defaults 0 1")
    if boot_dev := boot_device.get("boot"):
        lines.append(f"{_fstab_source(boot_dev)} /boot ext4 defaults 0 2")
    if boot_mode.lower() == "uefi" and efi_dir and (efi_dev := boot_device.get("efi")):
        lines.append(f"{_fstab_source(efi_dev)} {efi_dir.as_posix()} vfat umask=0077 0 2")
    fstab_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return fstab_path


def write_system_identity(target: Path, hostname: str, locale: str, keymap: str, timezone: str) -> list[Path]:
    paths: list[Path] = []
    (target / "etc").mkdir(parents=True, exist_ok=True)
    (target / "etc/hostname").write_text(f"{hostname}\n", encoding="utf-8")
    (target / "etc/locale.gen").write_text(f"{locale} UTF-8\n", encoding="utf-8")
    (target / "etc/locale.conf").write_text(f"LANG={locale}\n", encoding="utf-8")
    (target / "etc/vconsole.conf").write_text(f"KEYMAP={keymap}\n", encoding="utf-8")
    localtime = target / "etc/localtime"
    if localtime.exists() or localtime.is_symlink():
        localtime.unlink()
    localtime.symlink_to(Path("..") / "usr/share/zoneinfo" / timezone)
    paths.extend([target / "etc/hostname", target / "etc/locale.gen", target / "etc/locale.conf", target / "etc/vconsole.conf", localtime])
    return paths


def write_network_config(target: Path, backend: str = "NetworkManager", use_iwd: bool = False) -> list[Path]:
    if backend in {"NetworkManager", "iwd"}:
        nm_conf = target / "etc/NetworkManager/conf.d/10-lpm.conf"
        nm_conf.parent.mkdir(parents=True, exist_ok=True)
        content = "[main]\nplugins=keyfile\n"
        if use_iwd or backend == "iwd":
            content += "wifi.backend=iwd\n"
        nm_conf.write_text(content, encoding="utf-8")
        return [nm_conf]
    networkd = target / "etc/systemd/network/20-wired.network"
    networkd.parent.mkdir(parents=True, exist_ok=True)
    networkd.write_text("[Match]\nName=en* eth*\n\n[Network]\nDHCP=yes\n", encoding="utf-8")
    return [networkd]


def generate_mkinitcpio(target: Path, kernel: str) -> list[Path]:
    written: list[Path] = []
    conf = target / "etc/mkinitcpio.conf"
    conf.parent.mkdir(parents=True, exist_ok=True)
    if not conf.exists():
        conf.write_text("HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)\n", encoding="utf-8")
        written.append(conf)
    preset = target / f"etc/mkinitcpio.d/{kernel}.preset"
    preset.parent.mkdir(parents=True, exist_ok=True)
    if not preset.exists():
        preset.write_text(
            f"ALL_kver=\"/boot/vmlinuz-{kernel}\"\nPRESETS=('default')\ndefault_image=\"/boot/initramfs-{kernel}.img\"\n",
            encoding="utf-8",
        )
        written.append(preset)
    return written


def grub_install_command(boot_mode: str, efi_dir: Path | None, boot_device: str | None) -> list[str]:
    if boot_mode.lower() == "uefi":
        if not efi_dir:
            raise ValueError("efi_dir required for UEFI grub installation")
        return ["grub-install", "--target=x86_64-efi", f"--efi-directory={efi_dir}", "--bootloader-id=Lumin"]
    if not boot_device:
        raise ValueError("--boot-device is required for BIOS mode")
    return ["grub-install", "--target=i386-pc", boot_device]


def verify_bootstrap(target: Path, kernel: str, boot_mode: str, package_count: int, devices: dict[str, str]) -> dict[str, object]:
    required = [target / "etc/fstab", target / "etc/hostname", target / "etc/locale.conf"]
    return {
        "target": str(target),
        "kernel_version": kernel,
        "boot_mode": boot_mode,
        "package_count": package_count,
        "uuids": {name: _blkid_uuid(dev) for name, dev in devices.items()},
        "missing": [str(path) for path in required if not path.exists()],
        "next_steps": ["chroot and set root password", "reboot into installed system"],
    }


def generate_chroot_command(target: Path, command: list[str]) -> list[str]:
    return ["chroot", str(target), *command]


def generate_lpm_root_install_command(target: Path, packages: list[str]) -> list[str]:
    if not packages:
        raise ValueError("at least one package is required for lpm root install")
    return ["lpm", "--root", str(target), "install", *packages]


def _parse_pkg_list(value: Any) -> tuple[str, ...]:
    if value is None:
        return ()
    if isinstance(value, str):
        return tuple(p.strip() for p in value.split(",") if p.strip())
    if isinstance(value, (list, tuple)):
        return tuple(str(p).strip() for p in value if str(p).strip())
    return ()


def _bootstrap_packages(cfg: BootstrapConfig, kernel: str, network_backend: str, bootloader: str, state: Dict[str, Any]) -> list[str]:
    resolution = state.get("plan_resolution") if isinstance(state, dict) else None
    if isinstance(resolution, dict):
        resolved = resolution.get("package_order")
        if isinstance(resolved, list):
            pkgs = [str(p).strip() for p in resolved if str(p).strip()]
            if pkgs:
                return pkgs

    raw = getattr(cfg, "base_packages", None)
    custom = list(_parse_pkg_list(raw))
    if custom:
        return custom

    pkgs = ["basesystem", kernel, bootloader]
    if network_backend in {"NetworkManager", "iwd"}:
        pkgs.append("NetworkManager")
    return pkgs


def _extract_depends_from_lpmbuild(script_path: Path) -> list[str]:
    text = script_path.read_text(encoding="utf-8")
    matches = re.findall(r"(?m)^\s*depends\s*=\s*\(([^)]*)\)", text)
    deps: list[str] = []
    for raw in matches:
        deps.extend(re.findall(r"[\"']([^\"']+)[\"']", raw))
    return [d.strip() for d in deps if d.strip()]


def _resolve_from_lpmbuild_root(root: Path) -> list[str]:
    scripts = sorted(root.glob("**/*.lpmbuild"))
    graph: dict[str, set[str]] = {}
    indegree: dict[str, int] = defaultdict(int)
    reverse: dict[str, set[str]] = defaultdict(set)
    names: set[str] = set()

    for script in scripts:
        name = script.stem
        names.add(name)
        deps = [d for d in _extract_depends_from_lpmbuild(script) if d in names or (root / d / f"{d}.lpmbuild").exists()]
        graph[name] = set(deps)

    for pkg, deps in graph.items():
        indegree[pkg] = len(deps)
        for dep in deps:
            reverse[dep].add(pkg)

    queue = deque(sorted(pkg for pkg in graph if indegree[pkg] == 0))
    order: list[str] = []
    while queue:
        cur = queue.popleft()
        order.append(cur)
        for nxt in sorted(reverse.get(cur, set())):
            indegree[nxt] -= 1
            if indegree[nxt] == 0:
                queue.append(nxt)

    if len(order) != len(graph):
        unresolved = sorted(set(graph) - set(order))
        raise ValueError(f"cycle or unresolved dependency in lpmbuild metadata: {', '.join(unresolved)}")
    return order


def _resolve_build_plan(cfg: BootstrapConfig, state: Dict[str, Any]) -> Dict[str, Any]:
    if not cfg.plan_file and not cfg.lpmbuild_root and not cfg.include_packages and not cfg.exclude_packages:
        return {}

    package_order: list[str] = []
    source = ""
    if cfg.plan_file:
        payload = json.loads(cfg.plan_file.read_text(encoding="utf-8"))
        if isinstance(payload, dict):
            raw = payload.get("package_order") or payload.get("packages") or []
        else:
            raw = payload
        if not isinstance(raw, list):
            raise ValueError("plan file must be a list or contain package_order/packages list")
        package_order = [str(p).strip() for p in raw if str(p).strip()]
        source = f"plan-file:{cfg.plan_file}"
    elif cfg.lpmbuild_root:
        package_order = _resolve_from_lpmbuild_root(cfg.lpmbuild_root)
        source = f"lpmbuild-root:{cfg.lpmbuild_root}"

    include = set(cfg.include_packages)
    exclude = set(cfg.exclude_packages)
    if include:
        package_order = [p for p in package_order if p in include]
    if exclude:
        package_order = [p for p in package_order if p not in exclude]

    if not package_order:
        raise ValueError("resolved build plan produced an empty package list")

    return {
        "source": source,
        "package_order": package_order,
        "include_packages": sorted(include),
        "exclude_packages": sorted(exclude),
    }


def _as_path(value: Any) -> Optional[Path]:
    if value in (None, ""):
        return None
    return Path(str(value))


def _parse_toml(path: Path) -> Dict[str, Any]:
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        return {}
    section = data.get("bootstrap", data)
    return section if isinstance(section, dict) else {}


def load_config(cli_args: Any) -> BootstrapConfig:
    config_path = _as_path(getattr(cli_args, "config", None))
    toml_data: Dict[str, Any] = {}
    if config_path is not None and config_path.exists():
        toml_data = _parse_toml(config_path)

    def pick(name: str, default: Any = None) -> Any:
        cli_val = getattr(cli_args, name, None)
        return cli_val if cli_val is not None else toml_data.get(name, default)

    target = _as_path(pick("target"))
    if target is None:
        raise ValueError("bootstrap target is required")

    return BootstrapConfig(
        target=target,
        hostname=pick("hostname"),
        timezone=pick("timezone"),
        locale=pick("locale"),
        keymap=pick("keymap"),
        bootloader=pick("bootloader"),
        kernel=pick("kernel"),
        config=config_path,
        resume=bool(pick("resume", False)),
        dry_run=bool(pick("dry_run", False)),
        verbose=bool(pick("verbose", False)),
        force=bool(pick("force", False)),
        efi_dir=_as_path(pick("efi_dir")),
        boot_device=pick("boot_device"),
        network=pick("network"),
        plan_file=_as_path(pick("plan_file")),
        lpmbuild_root=_as_path(pick("lpmbuild_root")),
        include_packages=_parse_pkg_list(pick("include_packages")),
        exclude_packages=_parse_pkg_list(pick("exclude_packages")),
    )


def _log(cfg: BootstrapConfig, msg: str) -> None:
    if cfg.verbose or cfg.dry_run:
        print(f"[bootstrap] {msg}")


def _atomic_write_json(path: Path, payload: Dict[str, Any], dry_run: bool) -> None:
    if dry_run:
        print(f"[bootstrap][dry-run] write {path}: {json.dumps(payload, sort_keys=True)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as tf:
        json.dump(payload, tf, indent=2, sort_keys=True)
        tf.write("\n")
        tmp_name = tf.name
    os.replace(tmp_name, path)


def load_state(cfg: BootstrapConfig) -> Dict[str, Any]:
    if not cfg.state_path.exists():
        return {"completed_stages": []}
    return json.loads(cfg.state_path.read_text(encoding="utf-8"))


def save_state(cfg: BootstrapConfig, state: Dict[str, Any]) -> None:
    _atomic_write_json(cfg.state_path, state, cfg.dry_run)


def completed_stages(state: Dict[str, Any]) -> set[str]:
    raw = state.get("completed_stages", [])
    return {str(s) for s in raw if isinstance(s, str)}


def _run_stage(cfg: BootstrapConfig, stage: Stage, mount_state: ChrootMountState, state: Dict[str, Any]) -> Dict[str, Any]:
    _log(cfg, f"running stage={stage.value}")
    boot_mode = "uefi" if cfg.efi_dir else "bios"
    kernel = cfg.kernel or "linux"
    hostname = cfg.hostname or "localhost"
    locale = cfg.locale or "en_US.UTF-8"
    keymap = cfg.keymap or "us"
    timezone = cfg.timezone or "UTC"
    network_backend = cfg.network or "NetworkManager"
    bootloader = cfg.bootloader or "grub"
    devices: dict[str, str] = {}
    if cfg.boot_device:
        parts = [part.strip() for part in str(cfg.boot_device).split(",") if part.strip()]
        for part in parts:
            if "=" in part:
                k, v = part.split("=", 1)
                devices[k.strip().lower()] = v.strip()
            elif "root" not in devices:
                devices["root"] = part
    if stage == Stage.VALIDATE:
        if not cfg.target.exists() and not cfg.dry_run:
            raise FileNotFoundError(f"target does not exist: {cfg.target}")
        missing = [tool for tool in ("lpm", "chroot", "mount", "umount") if shutil.which(tool) is None]
        if missing:
            raise RuntimeError(f"missing required tools: {', '.join(missing)}")
        if boot_mode not in {"uefi", "bios"}:
            raise ValueError(f"unsupported boot mode: {boot_mode}")
        if boot_mode == "uefi" and cfg.efi_dir is None:
            raise ValueError("UEFI mode requires --efi-dir")
        if "root" not in devices and not cfg.dry_run:
            raise ValueError("boot device mapping must include root=DEVICE")
        if boot_mode == "uefi" and "efi" not in devices:
            _log(cfg, "warning: missing efi=DEVICE mapping; fstab/verification will omit EFI UUID")

    elif stage == Stage.PREPARE_DIRS:
        dirs = [cfg.target / "etc", cfg.target / "var", cfg.target / "usr", cfg.target / "boot"]
        if boot_mode == "uefi" and cfg.efi_dir is not None:
            dirs.append(cfg.target / cfg.efi_dir.relative_to("/") if cfg.efi_dir.is_absolute() else cfg.target / cfg.efi_dir)
        for d in dirs:
            if cfg.dry_run:
                print(f"[bootstrap][dry-run] mkdir -p {d}")
            else:
                d.mkdir(parents=True, exist_ok=True)
        if cfg.dry_run:
            print("[bootstrap][dry-run] mount chroot api filesystems")
        else:
            mount_chroot_api(cfg.target, mount_state)

    elif stage == Stage.SEED_LPM:
        src_root = Path(__file__).resolve().parents[1]
        dst_root = cfg.target / "usr/lib/lpm"
        if cfg.dry_run:
            print(f"[bootstrap][dry-run] seed lpm from {src_root} to {dst_root}")
        else:
            dst_root.mkdir(parents=True, exist_ok=True)
            subprocess.run(["cp", "-a", f"{src_root}/.", str(dst_root)], check=True)

    elif stage == Stage.RESOLVE_BUILD_PLAN:
        resolution = _resolve_build_plan(cfg, state)
        if resolution:
            state["plan_resolution"] = resolution
            _log(cfg, f"resolved plan source={resolution['source']} packages={len(resolution['package_order'])}")

    elif stage == Stage.INSTALL_BASE:
        cmd = generate_lpm_root_install_command(cfg.target, _bootstrap_packages(cfg, kernel, network_backend, bootloader, state))
        if cfg.dry_run:
            print(f"[bootstrap][dry-run] {' '.join(cmd)}")
        else:
            subprocess.run(cmd, check=True)

    elif stage == Stage.CONFIGURE_SYSTEM:
        if cfg.dry_run:
            print("[bootstrap][dry-run] write system identity/network/fstab")
        else:
            write_system_identity(cfg.target, hostname, locale, keymap, timezone)
            write_network_config(cfg.target, backend=network_backend, use_iwd=(network_backend == "iwd"))
            generate_fstab(cfg.target, boot_mode, cfg.efi_dir, devices)

    elif stage == Stage.GENERATE_INITRAMFS:
        if cfg.dry_run:
            print("[bootstrap][dry-run] generate mkinitcpio and run mkinitcpio -P in chroot")
        else:
            generate_mkinitcpio(cfg.target, kernel)
            subprocess.run(generate_chroot_command(cfg.target, ["mkinitcpio", "-P"]), check=True)

    elif stage == Stage.INSTALL_BOOTLOADER:
        if bootloader != "grub":
            raise ValueError(f"unsupported bootloader: {bootloader}")
        cmd = grub_install_command(boot_mode, cfg.efi_dir, devices.get("boot") or cfg.boot_device)
        chroot_cmd = generate_chroot_command(cfg.target, cmd)
        if cfg.dry_run:
            print(f"[bootstrap][dry-run] {' '.join(chroot_cmd)}")
        else:
            subprocess.run(chroot_cmd, check=True)

    elif stage == Stage.FINAL_CHECK:
        pkgs = _bootstrap_packages(cfg, kernel, network_backend, bootloader, state)
        summary = verify_bootstrap(cfg.target, kernel, boot_mode, package_count=len(pkgs), devices=devices)
        print(json.dumps(summary, sort_keys=True))
    return state


def run_bootstrap(args: Any) -> int:
    cfg = load_config(args)
    _safe_target(cfg.target)
    state = load_state(cfg)
    done = completed_stages(state)
    mount_state = ChrootMountState()

    try:
        for stage in STAGES:
            if cfg.resume and stage.value in done:
                _log(cfg, f"skip completed stage={stage.value}")
                continue
            state = _run_stage(cfg, stage, mount_state, state)
            done.add(stage.value)
            state["completed_stages"] = sorted(done)
            save_state(cfg, state)
        return 0
    finally:
        if not cfg.dry_run:
            try:
                umount_chroot_api(cfg.target, mount_state)
            except Exception as exc:
                print(f"[bootstrap] warning: failed to unmount API mounts: {exc}")
