from __future__ import annotations

import json
import os
import subprocess
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Any, Dict, Optional

from lpm.chroot import ChrootMountState, mount_chroot_api, umount_chroot_api

import tomllib


class Stage(str, Enum):
    VALIDATE = "validate"
    PREPARE_DIRS = "prepare-dirs"
    SEED_LPM = "seed-lpm"
    INSTALL_BASE = "install-base"
    CONFIGURE_SYSTEM = "configure-system"
    GENERATE_INITRAMFS = "generate-initramfs"
    INSTALL_BOOTLOADER = "install-bootloader"
    FINAL_CHECK = "final-check"


STAGES: list[Stage] = [
    Stage.VALIDATE,
    Stage.PREPARE_DIRS,
    Stage.SEED_LPM,
    Stage.INSTALL_BASE,
    Stage.CONFIGURE_SYSTEM,
    Stage.GENERATE_INITRAMFS,
    Stage.INSTALL_BOOTLOADER,
    Stage.FINAL_CHECK,
]


@dataclass
class BootstrapConfig:
    target: Path
    hostname: Optional[str] = None
    timezone: Optional[str] = None
    locale: Optional[str] = None
    keymap: Optional[str] = None
    bootloader: Optional[str] = None
    kernel: Optional[str] = None
    config: Optional[Path] = None
    resume: bool = False
    dry_run: bool = False
    verbose: bool = False
    force: bool = False
    efi_dir: Optional[Path] = None
    boot_device: Optional[str] = None
    network: Optional[str] = None

    @property
    def state_path(self) -> Path:
        return self.target / "var/lib/lpm/bootstrap-state.json"


def _safe_target(target: Path) -> None:
    resolved = target.resolve()
    if str(resolved) in {"/", "/etc", "/usr", "/var", "/boot"}:
        raise ValueError(f"refusing dangerous target: {resolved}")


def _blkid_uuid(device: str) -> str | None:
    try:
        completed = subprocess.run(["blkid", "-s", "UUID", "-o", "value", device], check=False, capture_output=True, text=True)
    except OSError:
        return None
    return completed.stdout.strip() if completed.returncode == 0 and completed.stdout.strip() else None


def _fstab_source(device: str) -> str:
    return f"UUID={uuid}" if (uuid := _blkid_uuid(device)) else device


def generate_fstab(target: Path, boot_mode: str, efi_dir: Path | None, boot_device: dict[str, str]) -> Path:
    fstab_path = target / "etc/fstab"
    fstab_path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# /etc/fstab generated by lpm bootstrap"]
    if root_dev := boot_device.get("root"):
        lines.append(f"{_fstab_source(root_dev)} / ext4 defaults 0 1")
    if boot_dev := boot_device.get("boot"):
        lines.append(f"{_fstab_source(boot_dev)} /boot ext4 defaults 0 2")
    if boot_mode.lower() == "uefi" and efi_dir and (efi_dev := boot_device.get("efi")):
        lines.append(f"{_fstab_source(efi_dev)} {efi_dir.as_posix()} vfat umask=0077 0 2")
    fstab_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return fstab_path


def write_system_identity(target: Path, hostname: str, locale: str, keymap: str, timezone: str) -> list[Path]:
    paths: list[Path] = []
    (target / "etc").mkdir(parents=True, exist_ok=True)
    (target / "etc/hostname").write_text(f"{hostname}\n", encoding="utf-8")
    (target / "etc/locale.gen").write_text(f"{locale} UTF-8\n", encoding="utf-8")
    (target / "etc/locale.conf").write_text(f"LANG={locale}\n", encoding="utf-8")
    (target / "etc/vconsole.conf").write_text(f"KEYMAP={keymap}\n", encoding="utf-8")
    localtime = target / "etc/localtime"
    if localtime.exists() or localtime.is_symlink():
        localtime.unlink()
    localtime.symlink_to(Path("..") / "usr/share/zoneinfo" / timezone)
    paths.extend([target / "etc/hostname", target / "etc/locale.gen", target / "etc/locale.conf", target / "etc/vconsole.conf", localtime])
    return paths


def write_network_config(target: Path, backend: str = "NetworkManager", use_iwd: bool = False) -> list[Path]:
    if backend in {"NetworkManager", "iwd"}:
        nm_conf = target / "etc/NetworkManager/conf.d/10-lpm.conf"
        nm_conf.parent.mkdir(parents=True, exist_ok=True)
        content = "[main]\nplugins=keyfile\n"
        if use_iwd or backend == "iwd":
            content += "wifi.backend=iwd\n"
        nm_conf.write_text(content, encoding="utf-8")
        return [nm_conf]
    networkd = target / "etc/systemd/network/20-wired.network"
    networkd.parent.mkdir(parents=True, exist_ok=True)
    networkd.write_text("[Match]\nName=en* eth*\n\n[Network]\nDHCP=yes\n", encoding="utf-8")
    return [networkd]


def generate_mkinitcpio(target: Path, kernel: str) -> list[Path]:
    written: list[Path] = []
    conf = target / "etc/mkinitcpio.conf"
    conf.parent.mkdir(parents=True, exist_ok=True)
    if not conf.exists():
        conf.write_text("HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)\n", encoding="utf-8")
        written.append(conf)
    preset = target / f"etc/mkinitcpio.d/{kernel}.preset"
    preset.parent.mkdir(parents=True, exist_ok=True)
    if not preset.exists():
        preset.write_text(
            f"ALL_kver=\"/boot/vmlinuz-{kernel}\"\nPRESETS=('default')\ndefault_image=\"/boot/initramfs-{kernel}.img\"\n",
            encoding="utf-8",
        )
        written.append(preset)
    return written


def grub_install_command(boot_mode: str, efi_dir: Path | None, boot_device: str | None) -> list[str]:
    if boot_mode.lower() == "uefi":
        if not efi_dir:
            raise ValueError("efi_dir required for UEFI grub installation")
        return ["grub-install", "--target=x86_64-efi", f"--efi-directory={efi_dir}", "--bootloader-id=Lumin"]
    if not boot_device:
        raise ValueError("--boot-device is required for BIOS mode")
    return ["grub-install", "--target=i386-pc", boot_device]


def verify_bootstrap(target: Path, kernel: str, boot_mode: str, package_count: int, devices: dict[str, str]) -> dict[str, object]:
    required = [target / "etc/fstab", target / "etc/hostname", target / "etc/locale.conf"]
    return {
        "target": str(target),
        "kernel_version": kernel,
        "boot_mode": boot_mode,
        "package_count": package_count,
        "uuids": {name: _blkid_uuid(dev) for name, dev in devices.items()},
        "missing": [str(path) for path in required if not path.exists()],
        "next_steps": ["chroot and set root password", "reboot into installed system"],
    }


def generate_chroot_command(target: Path, command: list[str]) -> list[str]:
    return ["chroot", str(target), *command]


def _as_path(value: Any) -> Optional[Path]:
    if value in (None, ""):
        return None
    return Path(str(value))


def _parse_toml(path: Path) -> Dict[str, Any]:
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        return {}
    section = data.get("bootstrap", data)
    return section if isinstance(section, dict) else {}


def load_config(cli_args: Any) -> BootstrapConfig:
    config_path = _as_path(getattr(cli_args, "config", None))
    toml_data: Dict[str, Any] = {}
    if config_path is not None and config_path.exists():
        toml_data = _parse_toml(config_path)

    def pick(name: str, default: Any = None) -> Any:
        cli_val = getattr(cli_args, name, None)
        return cli_val if cli_val is not None else toml_data.get(name, default)

    target = _as_path(pick("target"))
    if target is None:
        raise ValueError("bootstrap target is required")

    return BootstrapConfig(
        target=target,
        hostname=pick("hostname"),
        timezone=pick("timezone"),
        locale=pick("locale"),
        keymap=pick("keymap"),
        bootloader=pick("bootloader"),
        kernel=pick("kernel"),
        config=config_path,
        resume=bool(pick("resume", False)),
        dry_run=bool(pick("dry_run", False)),
        verbose=bool(pick("verbose", False)),
        force=bool(pick("force", False)),
        efi_dir=_as_path(pick("efi_dir")),
        boot_device=pick("boot_device"),
        network=pick("network"),
    )


def _log(cfg: BootstrapConfig, msg: str) -> None:
    if cfg.verbose or cfg.dry_run:
        print(f"[bootstrap] {msg}")


def _atomic_write_json(path: Path, payload: Dict[str, Any], dry_run: bool) -> None:
    if dry_run:
        print(f"[bootstrap][dry-run] write {path}: {json.dumps(payload, sort_keys=True)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as tf:
        json.dump(payload, tf, indent=2, sort_keys=True)
        tf.write("\n")
        tmp_name = tf.name
    os.replace(tmp_name, path)


def load_state(cfg: BootstrapConfig) -> Dict[str, Any]:
    if not cfg.state_path.exists():
        return {"completed_stages": []}
    return json.loads(cfg.state_path.read_text(encoding="utf-8"))


def save_state(cfg: BootstrapConfig, state: Dict[str, Any]) -> None:
    _atomic_write_json(cfg.state_path, state, cfg.dry_run)


def completed_stages(state: Dict[str, Any]) -> set[str]:
    raw = state.get("completed_stages", [])
    return {str(s) for s in raw if isinstance(s, str)}


def _run_stage(cfg: BootstrapConfig, stage: Stage, mount_state: ChrootMountState) -> None:
    _log(cfg, f"running stage={stage.value}")
    if stage == Stage.VALIDATE and not cfg.target.exists() and not cfg.dry_run:
        raise FileNotFoundError(f"target does not exist: {cfg.target}")
    if stage == Stage.PREPARE_DIRS:
        if cfg.dry_run:
            print("[bootstrap][dry-run] mount chroot api filesystems")
        else:
            mount_chroot_api(cfg.target, mount_state)
    if stage == Stage.SEED_LPM and cfg.dry_run:
        print("[bootstrap][dry-run] package plan: seed lpm into target")
    if stage == Stage.INSTALL_BASE and cfg.dry_run:
        print("[bootstrap][dry-run] package plan: install base system")


def run_bootstrap(args: Any) -> int:
    cfg = load_config(args)
    _safe_target(cfg.target)
    state = load_state(cfg)
    done = completed_stages(state)
    mount_state = ChrootMountState()

    try:
        for stage in STAGES:
            if cfg.resume and stage.value in done:
                _log(cfg, f"skip completed stage={stage.value}")
                continue
            _run_stage(cfg, stage, mount_state)
            done.add(stage.value)
            save_state(cfg, {"completed_stages": sorted(done)})
        return 0
    finally:
        if not cfg.dry_run:
            try:
                umount_chroot_api(cfg.target, mount_state)
            except Exception as exc:
                print(f"[bootstrap] warning: failed to unmount API mounts: {exc}")
